export type IDType = "nin" | "bvn" | "passport" | "drivers_license";
export type AccountType = "Savings" | "Current";

export type FormData = {
  firstName: string;
  lastName: string;
  dob: Date | string;
  gender?: "Male" | "Female";
  email: string;
  phone: string;
  country: string;
  maritalStatus: string;
  alternatePhone?: string;
  employmentStatus?: string;
  tin: string;
  state: string;
  address: string;
  idType?: IDType;
  idNumber?: string;
  idDocument?: File | string | null;
  idType2?: IDType;
  expiryDate: Date | string;
  issuingAuthority: string;
  issuingAuthorityPOA: string;
  idNumber2?: string;
  idDocument2?: File | string | null;
  proofOfAddress?: File | string | null;
  dateOfIssue: Date | string;
  addressProofType?: string;
  profileImage?: File | string | null;
  branch?: string;
  accountOfficer?: string;
  desiredAccount?: AccountType;
  employerAddress: string;
  jobTitle: string;
  startDate: Date | string;
  endDate: Date | string;
  employmentDocument: File | string | null;
  guarantorFullName: string;
  guarantorRelationship: string;
  guarantorPhone: string;
  guarantorEmail: string;
  guarantorAddress: string;
  guarantorId: File | string | null;
  nextOfKinFullName: string;
  nextOfKinPhone: string;
  nextOfKinEmail: string;
  nextOfKinAddress: string;
  nextOfKinRelationship: string;
};

export type FormContextType = {
  formData: FormData;
  updateFormData: (data: Partial<FormData>) => void;
};
export type BusinessFormData = {
  businessName: string;
  businessType: string;
  businessAddress: string;
  email: string;
  phoneNumber: string;
  branch: string;
  desiredAccount: AccountType;
  accountOfficer: string;
  registrationNumber: string;
  tin: string;
  natureOfBusiness: string;
  website: string;
  businessIncorporationCertificate: File | string | null;
  memorandumArticles: File | string | null;
  businessLicense: File | string | null;
  utilityBillType: string;
  utilityBillIssuer: string;
  issueDateOfBill: Date;
  utilityBill: File | string | null;
};

export type Country = {
  id: number;
  name: string;
  iso3: string;
  iso2: string;
  numeric_code: string;
  phone_code: string;
  capital: string;
  currency: string;
  currency_name: string;
  currency_symbol: string;
  native: string;
  region: string;
  subregion: string;
  emoji: string;
  emojiU: string;
  tld: string;
  latitude: string;
  longitude: string;
};

export type State = {
  id: number;
  name: string;
  state_code: string;
  latitude: string;
  longitude: string;
};
